### ISSUE TITLE
Fix JavaScript side effect

### ISSUE THREAD

**Issue by root-hbx** [TechFounders-Berkeley/TechFounders-Web#6]
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/301df388-ecf5-40ec-a9f9-495ab38440c8">

Currently, when we click the logo here, it shows `javascript:void(0)` at the bottom left corner of the webpage.

This phenomenon indicates that the side effect of clicking logo is set to null. Could we set the JavaScript side effect here to **redirect to the homepage** of the respective company? @Yaowwwwww

**Comment by quyB2105718** [comment]
can i try to do it, i want to learn about this

**Comment by root-hbx** [comment]
> can i try to do it, i want to learn about this

Of course, pls feel free to solve this and try to give a new pr after you finish :)

**Comment by root-hbx** [comment]
Fixed by #9 , thanks @quyB2105718 . Looking forward to your contribution to the project!
